# 配置文件版本 / Configuration version
version: 1.3

# 是否启用插件 / Whether to enable the plugin
# true 表示启用插件，false 表示禁用插件
# enable plugin, true / false
enable_plugin: true

# Language / 语言
# 可用列表 / Available languages: zh_hans / zh_hant / en_us / ja_jp
language: zh_hans

# 配置列表
configlist:

  test1:  # 配置名称 / configuration name
    enabled: false  # 启用此配置 / enable this config
    tick_delay: 0 # 延迟几tick后才进行判断 / delay ticks before checking
    execute:  # 执行条件 / execute conditions

      - permission: meowjoincommand.test1  
          # 权限条件：玩家需要拥有 "meowjoincommand.test1" 权限
          # permission execution condition: player need to have "meowjoincommand.test1" permission

      - permission: meowjoincommand.test0
          # 权限条件：玩家需要拥有 "meowjoincommand.test0" 权限
          # permission execution condition: player need to have "meowjoincommand.test0" permission

      - money: ">50"
          # 金钱条件：玩家金钱大于 50 
          # money execution condition: player money greater than 50

      - placeholderapi: "%some_placeholder% = some_value" 
          # 占位符条件：%some_placeholder% 变量的值等于 some_value
          # placeholder execution condition: %some_placeholder% placeholder value equals some_value

      - placeholderapi: "%some_placeholder% != some_value" 
          # 占位符条件：%some_placeholder% 变量的值不等于 some_value
          # placeholder execution condition: %some_placeholder% placeholder value not equals some_value

    commands:  
      # 满足条件后的执行指令
      # commands after execution

      - type: player  
          # 以玩家身份执行 
          # executed as a player

        command: say Hello, %player%! 
          # 玩家执行的指令，%player% 会被替换为玩家名 
          # command executed as a player, %player% will be replaced with player name

        tick_delay: 5 
          # 延迟几tick后执行 
          # executed after delaying for a few ticks

      - type: console  
          # 以服务器身份执行 
          # executed as a server

        command: tell %player%, Welcome to the server! 
          # 服务器执行的指令，%player% 会被替换为玩家名 
          # command executed as a server, %player% will be replaced with player name

        tick_delay: 5 
          # 延迟几tick后执行 
          # executed after delaying for a few ticks

  test2: 
    enabled: false  
    tick_delay: 0 
    execute: 
      - permission: meowjoincommand.test2 
    commands: 
      - type: player 
        command: say Hello, %player%!  
        tick_delay: 10
      - type: console  
        command: money give %player% 100 
        tick_delay: 10
        
# 执行条件支持 permission 、 placeholderapi 和 money
# money 的判断符号支持>=  > =  <=  <
# placeholderapi 的判断符号支持 = 或 !=
# command type 支持 player 及 console，分别为以玩家及服务器权限执行指令
# %player% 会被自动替换为玩家名
# 顶层的 tick_delay 为延迟几tick后才进行判断
# commands 中的 tick_delay 为延迟几tick后执行指令，在TPS为20时一秒可以执行20tick
# 如果执行条件中存在多项要求，则需全部满足才会执行指令

# Execution conditions support permission, placeholderapi and money
# The money judgment symbol supports >= > = <= <
# The placeholderapi judgment symbol supports = or !=
# Command type supports player and console, which means executing commands with player or server permissions
# %player% will be automatically replaced with the player's name
# The top tick_delay is the delay in ticks before checking
# The tick_delay in commands is the delay in ticks before executing the command, which can be executed 20 ticks per second with TPS=20
# If there are multiple requirements in the execution conditions, they must all be satisfied before the command is executed
# Configuration file English content is translated by TONGYI Lingma