version: 1.0  # 配置文件版本
enable_plugin: false  # 是否启用插件，默认不启用

configlist:  # 配置列表
  test1:  # 配置名
    enabled: false  # 是否启用此配置项，设置为 true 则启用此配置
    execute:  # 执行条件
      - permission: meowjoincommand.test1  # 权限条件：玩家需要拥有 meowjoincommand.test1 权限
      - permission: meowjoincommand.test0  # 权限条件：玩家需要拥有 meowjoincommand.test0 权限
      - money: ">50"  # 金钱条件：玩家金钱大于 50（支持 >, <, >=, <=, == 等符号）
    commands:  # 满足条件后的执行指令
      - type: player  # 以玩家身份执行
        command: say Hello!  # 玩家执行的指令
      - type: console  # 以服务器身份执行
        command: tell %player%, welcome!  # 服务器执行的指令，%player% 会被替换为玩家名

  test2:  # 配置名
    enabled: false  # 是否启用此配置项，设置为 true 则启用此配置
    execute:  # 执行条件
      - permission: meowjoincommand.test2  # 权限条件：玩家需要拥有 meowjoincommand.test2 权限
    commands:  # 满足条件后的执行指令
      - type: player  # 以玩家身份执行
        command: say hellllllllo  # 玩家执行的指令
      - type: console  # 以服务器身份执行
        command: money give %player% 100  # 服务器执行的指令，%player% 会被替换为玩家名

# 说明：
# - "permission" 条件用于判断玩家是否拥有指定权限
# - "money" 条件用于判断玩家的金钱（支持多种比较运算符，如 >、<、>=、<=、==）
# - "type" 指定执行指令的角色，"player" 为玩家，"console" 为服务器
# - "%player%" 会被自动替换为当前玩家的名字
