name: MeowJoinCommand
version: 1.3.2
main: com.meowjoincommand.MeowJoinCommand
api-version: 1.16
softdepend: ["PlaceholderAPI", "Vault"]
depend:
  - MeowLibs
commands:
  meowjoincommand:
    description: Main command
    usage: /<command> reload
    subcommands:
      reload:
        description: Reload the configuration file
        usage: /meowjoincommand reload
permissions:
  meowjoincommand.reload:
    description: Allows the player to reload the configuration file
    default: op
